---

- hosts: all
  become: true
  pre_tasks:
 
 #  The repository updates are generally a good idea
 #  before rolling out any packages:
  - name: install updates (CentOS)
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"
 
  - name: install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# Only roll out packages to certain systems
# "web_servers" is a group in the inventory file
- hosts: web_servers
  become: true
  tasks:

  - name: install apache and php for CentOS servers
    dnf:
      name:
        - httpd
        - php
      state: latest
    when: ansible_distribution == "CentOS"
 
  - name: install apache and php for Ubuntu servers
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
    when: ansible_distribution == "Ubuntu"


# Only roll out packages to certain systems
# "db_servers" is a group in the inventory file
- hosts: db_servers
  become: true
  tasks:

  - name: install mariadb package for Ubuntu
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install mariadb package for CentOS
    dnf:
      name: mariadb
      state: latest
    when: ansible_distribution == "CentOS"


# Only roll out packages to certain systems
# "file_servers" is a group in the inventory file
- hosts: file_servers
  become: true
  tasks:

  - name: install samba package for Ubuntu and CentOS
#   We can use the generic name "package" because the samba package
#   has the same name on both Ubuntu and CentOS (no "when" clause here)
    package:
      name: samba
      state: latest

